dist: trusty

language: node_js

node_js:
  - "8"
  - "9"

cache:
  directories:
    - node_modules

sudo: required

install:
  - npm install

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: build
      script: sh ./scripts/travis/build.sh
